name: Build & Deploy
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Build multi platform
              uses: dawidd6/action-docker-publish-changed@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  token: ${{secrets.DEPLOY_TOKEN}}
                  platforms: linux/amd64,linux/arm64,linux/arm
                  tag: latest